export default [
  "A dew-kissed meadow sings not of peace, but of footsteps forgotten by the shepherd.",
  "The flock may follow stars in the sky, yet trip on shadows beneath their hooves.",
  "The lamb that dances in moonlight knows not if it's praised… or prepared.",
  "A woolen hush cloaks the hillside, yet the silence gnaws like unseen teeth.",
  "Each bell tolls a lullaby, but beneath the melody lies a map of the blade.",
  "Where grass grows sweetest, the shepherd plants his lies with care.",
  "The sheep who questions the breeze finds storms in every whisper.",
  "Even shepherds sleep—but the pasture dreams of fire.",
  "A single black sheep in a sea of white is not alone—he is a mirror turned away.",
  "When the sky weeps gold and the earth swells green, beware—the shearing comes in spring.",
  "The shepherd sleeps, and the herd grazes on illusions. But wolves do not dream.",
  "One sheep strays, and the rest follow — not out of loyalty, but fear of thought.",
  "The silence of the pasture speaks louder than the bell of the flock.",
  "To shear a sheep is mercy. To let it wander unshorn is cruelty cloaked as kindness.",
  "Even the lamb believes itself sovereign… until it hears the gate close behind it.",
  "They bleat for freedom, yet beg for fences. Such is the nature of the herd.",
  "The shepherd smiles, not out of love, but because he counts more than sheep — he counts on them.",
  "In a world of wolves, the meek inherit the pasture… but only for a season.",
  "Some sheep dress in wool. Others wear the skins of shepherds.",
  "It is not the wolf who dooms the flock, but the sheep who teaches the others to kneel.",
];
